# splitlog.py
# Author: Aled Rhys Evans <evansar6@cardiff.ac.uk>
# License: Simplified BSD License (FreeBSD License) 
# Description: A simple utility to split logfiles generated by the CaptureHPC high-interaction honeypot framework
#              for malware analysis. Currently splits the logfiles into distinct blocks by date, as this seems to 
#              be the most reliable way in the absence of any significant delimiters. Documentation on CaptureHPC
#              is scarce, so if anyone knows of a better way to do this, please e-mail me. 

import csv, sys, os.path

if len(sys.argv) < 3:
    print "I/O Error: Need input and output files as arguments."
    exit(1)

if not os.path.exists(sys.argv[1]):
    print "I/O Error: input file doesn't exist."
    exit(1)

try:
    log = open(sys.argv[1], "rb")
    # Reading the file as a csv makes it easier for us to get the datestamps.
    reader = csv.reader(log)
except IOError as e:
    print "Unable to open input file."

print "Opened input file successfully."

try:
    out = open(sys.argv[2], "wb")
except IOError as e:
    print "Unable to open output file."

print "Opened output file successfully."
print "Splitting individual logs..."

init = 0
for line in reader:
    if init == 0:
        # Storing the initial timestamp here.
        lastStamp = ""
        i = 0
        # line[1] holds the date/timestamps. We cut off at the first blank character to avoid including the timestamp.
        while line[1][i] is not ' ':
            lastStamp += str(line[1][i])
            i += 1
#        print lastStamp
        init += 1
        writeline = str(line).replace("[", "").replace("]", "").replace("'", "\"").replace("\\\\", "\\").replace(", ", ",")
        out.write(writeline)
        out.write('\n')
    else:
        currentStamp = ""
        i = 0
        while line[1][i] is not ' ':
            currentStamp += str(line[1][i])
            i += 1
        if str(currentStamp) == str(lastStamp):
            lastStamp = currentStamp
            writeline = str(line).replace("[", "").replace("]", "").replace("'", "\"").replace("\\\\", "\\").replace(", ", ",")
            out.write(writeline)
            out.write('\n')
        else:
            lastStamp = currentStamp
            out.write('\n')
            writeline = str(line).replace("[", "").replace("]", "").replace("'", "\"").replace("\\\\", "\\").replace(", ", ",")
            out.write(writeline)
            out.write('\n')

print "Finished. Closing files."
log.close()
out.close()
print "Files closed."
