class mailvir:
    def __init__(self):
        self.procstart = ['C:\Users\mp\AppData\Local\Temp\\fqcuk.dll',
                'C:\Users\mp\AppData\Roaming\Qohezy\zeve.exe',
                'C:\Program Files\Windows Mail\WinMail.exe',
                'C:\Users\mp\AppData\Local\Temp\BHDG.dll']
        self.procterm = ['C:\Users\mp\AppData\Local\Temp\\fqcuk.dll']
        self.regset = ['HKCU\Software\Microsoft\Internet Explorer\LowRegistry\ErrorReporting\LastShipAssertTime',
                'HKCU',
                '\REGISTRY\A\{511E200C-167F-11E4-9376-080027E9ED50}\DefaultObjectStore\IndexTable\FileIdIndex-{41003fa5-89a3-11e3-bfdc-806e6f6e6963}\_IndexName_',
                '\REGISTRY\A\{511E200C-167F-11E4-9376-080027E9ED50}\DefaultObjectStore\_CurrentObjectId_',
                '\REGISTRY\A\{511E200C-167F-11E4-9376-080027E9ED50}\DefaultObjectStore\ObjectTable\\13D\_ObjectId_',
                '\REGISTRY\A\{511E200C-167F-11E4-9376-080027E9ED50}\DefaultObjectStore\LruList\CurrentLru',
                '\REGISTRY\A\{511E200C-167F-11E4-9376-080027E9ED50}\DefaultObjectStore\LruList\\0000000000000B73\ObjectId',
                '\REGISTRY\A\{511E200C-167F-11E4-9376-080027E9ED50}\DefaultObjectStore\LruList\\0000000000000B73\ObjectLru',
                '\REGISTRY\A\{511E200C-167F-11E4-9376-080027E9ED50}\DefaultObjectStore\ObjectTable\\13D\_ObjectLru_',
                '\REGISTRY\A\{511E200C-167F-11E4-9376-080027E9ED50}\DefaultObjectStore\ObjectTable\\13D\_FileId_',
                '\REGISTRY\A\{511E200C-167F-11E4-9376-080027E9ED50}\DefaultObjectStore\ObjectTable\\13D\_Usn_',
                '\REGISTRY\A\{511E200C-167F-11E4-9376-080027E9ED50}\DefaultObjectStore\ObjectTable\\13D\_UsnJournalId_',
                '\REGISTRY\A\{511E200C-167F-11E4-9376-080027E9ED50}\DefaultObjectStore\ObjectTable\\13D\Indexes\FileIdIndex-{41003fa5-89a3-11e3-bfdc-806e6f6e6963}\900000000A149',
                '\REGISTRY\A\{511E200C-167F-11E4-9376-080027E9ED50}\DefaultObjectStore\IndexTable\FileIdIndex-{41003fa5-89a3-11e3-bfdc-806e6f6e6963}\900000000A149\\13D',
                '\REGISTRY\A\{511E200C-167F-11E4-9376-080027E9ED50}\DefaultObjectStore\ObjectTable\\13D\AeFileID',
                '\REGISTRY\A\{511E200C-167F-11E4-9376-080027E9ED50}\DefaultObjectStore\ObjectTable\\13D\AeProgramID',
                'HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\\3\\1406',
                'HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\\1\\1609',
                'HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\\4\\1A02',
                'HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\\2\\1A10',
                'HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\\4\\1A10',
                'HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\\4\\1A03',
                'HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\\3\\1A05',
                'HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\\4\\1A05',
                'HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\\4\\1A06',
                'HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings\Lockdown_Zones\\0\\1609'
                'HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings\WarnonBadCertRecving',
                'HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings\EnableSPDY3_0',
                'HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings\ZoneMap\UNCAsIntranet',
                'HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings\ZoneMap\AutoDetect',
                'HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\\0\\1609',
                'HKCU\Software\Microsoft\Nylaiw\Fauzwua',
                'HKCU\Software\Microsoft\Nylaiw\Upcaolap',
                'HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings\ProxyEnable',
                'HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings\Connections\SavedLegacySettings',
                'HKCU\Software\Microsoft\IAM\Accounts\ConnectionSettingsMigrated',
                'HKCU\Software\Microsoft\Windows Mail\Trident\Main\Move System Caret',
                'HKCU\Software\Microsoft\Windows Mail\StoreMigratedV5',
                'HKCU\Software\Microsoft\Windows Mail\Settings Upgraded',
                'HKCU\Software\Microsoft\Windows Mail\Mail\Safe Attachments',
                'HKCU\Software\Microsoft\Windows Mail\Mail\Secure Safe Attachments',
                'HKCU\Software\Microsoft\Windows Mail\Running',
                'HKCU\Software\Microsoft\IAM\Default LDAP Account',
                'HKCU\Software\Microsoft\IAM\Server ID',
                'HKCU\Identities\{ACC29697-975F-4790-9CF9-A615892A2859}\Identity Ordinal',
                'HKCU\Identities\Identity Ordinal',
                'HKCU\Software\Microsoft\Windows Mail\LastBackup',
                'HKCU\Software\Microsoft\Windows Mail\V7StoreMigDone',
                'HKCU\Software\Microsoft\IAM\Default News Account',
                'HKCU\Software\Microsoft\WAB\NamedProps',
                'HKCU\Software\Microsoft\WAB\NamedPropCount',
                'HKCU\Software\Microsoft\Windows Mail\Mail\Welcome Message',
                'HKCU\Software\Microsoft\Windows Mail\Junk Mail\Safe Senders List\Version',
                'HKCU\Software\Microsoft\Windows Mail\Junk Mail\Block Senders List\Version',
                'HKCU\Software\Microsoft\IdentityCRL\Dynamic Salt\Value',
                'HKCU\Software\Microsoft\IdentityCRL\Dynamic Salt\Size',
                'HKCR\Local Settings\MuiCache\B\\52C64B7E\LanguageList',
                'HKCU\Software\Microsoft\Windows Mail\SpoolerDlgPos',
                'HKCU\Software\Microsoft\Windows Mail\SpoolerTack',
                'HKCU\Software\Microsoft\Windows Mail\Mail\Default_CodePage',
                'HKCU\Software\Microsoft\Windows Mail\Compact Check Count',
                'HKCU\Software\Microsoft\Windows Mail\LastRun',
                ]

        self.regdel = ['HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings\ZoneMap\ProxyBypass',
                'HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Internet Settings\ZoneMap\ProxyBypass',
                'HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings\ZoneMap\IntranetName',
                'HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Internet Settings\ZoneMap\IntranetName',
                'HKCU\Software\Microsoft\Windows\CurrentVersion\Run\zeve.exe',
                'HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings\ProxyServer',
                'HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings\ProxyOverride',
                'HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings\AutoConfigURL',
                'HKCU\Identities\OutgoingID',
                'HKCU\Identities\Changing',
                'HKCU\Identities\IncomingID',
                'HKCU\Software\Microsoft\WAB\NamedProps',
                'HKCU\Software\Microsoft\WAB\NamedPropCount',
                ]
        self.filewrite = ['C:\Users\mp\AppData\Local\Temp\\fqcuk.dll',
                'C:\Users\mp\AppData\Roaming\Qohezy\zeve.exe',
                'C:\Windows\AppCompat\Programs\RecentFileCache.bcf',
                'C:\Users\mp\AppData\Local\Temp\\tmp4632b6f2.bat',
                'C:\Program Files\Capture\logs\deleted_files\C\Users\mp\AppData\Local\Temp\\tmp4632b6f2.bat',
                'C:\Users\mp\AppData\Local\Temp\BHDG.dll',
                'C:\Users\mp\AppData\Local\Microsoft\Windows Mail\edb.log',
                'C:\Users\mp\AppData\Local\Microsoft\Windows Mail\\tmp.edb',
                'C:\Users\mp\AppData\Local\Microsoft\Windows Mail\WindowsMail.MSMessageStore',
                'C:\Users\mp\AppData\Local\Microsoft\Windows Mail\Backup\\temp\WindowsMail.MSMessageStore',
                'C:\Users\mp\AppData\Local\Microsoft\Windows Mail\edbtmp.log',
                'C:\Users\mp\AppData\Local\Microsoft\Windows Mail\WindowsMail.pat',
                'C:\Users\mp\AppData\Local\Microsoft\Windows Mail\Backup\\temp\edb00002.log',
                'C:\Users\mp\AppData\Local\Microsoft\Windows Mail\Backup\\temp\WindowsMail.pat',
                'C:\Users\mp\AppData\Local\Microsoft\Windows Mail\Local Folders\Inbox\winmail.fol',
                'C:\Users\mp\AppData\Local\Microsoft\Windows Mail\Local Folders\Outbox\winmail.fol',
                'C:\Users\mp\AppData\Local\Microsoft\Windows Mail\Local Folders\Sent Items\winmail.fol',
                'C:\Users\mp\AppData\Local\Microsoft\Windows Mail\Local Folders\Deleted Items\winmail.fol',
                'C:\Users\mp\AppData\Local\Microsoft\Windows Mail\Local Folders\Drafts\winmail.fol',
                'C:\Users\mp\AppData\Local\Microsoft\Windows Mail\Local Folders\Junk E-mail\winmail.fol',
                'C:\Users\mp\AppData\Local\Microsoft\Windows Mail\Local Folders\Inbox\\4F8B02F0-00000001.eml',
                'C:\Users\mp\AppData\Roaming\Microsoft\Protect\S-1-5-21-78034117-1329648361-637219273-1001\\3aed1323-c5d3-4c4a-979c-78f92d2e3e2b',
                'C:\Users\mp\AppData\Roaming\Microsoft\Protect\S-1-5-21-78034117-1329648361-637219273-1001\Preferred',
                'C:\Users\mp\AppData\LocalLow\Microsoft\CryptnetUrlCache\MetaData\E6024EAC88E6B6165D49FE3C95ADD735',
                'C:\Users\mp\AppData\LocalLow\Microsoft\CryptnetUrlCache\Content\E6024EAC88E6B6165D49FE3C95ADD735',
                'C:\Users\mp\AppData\Local\Temp\CabF8E.tmp',
                'C:\Users\mp\AppData\Local\Temp\TarF8F.tmp',
                'C:\Users\mp\AppData\Local\Temp\ppcrlui_3164_2',
                'C:\Users\mp\AppData\Local\Microsoft\Windows Mail\edb.chk'
                ]
        self.filedel = ['C:\Users\mp\AppData\Local\Microsoft\Windows Mail\Backup\old\edb00001.log',
                'C:\Users\mp\AppData\Local\Microsoft\Windows Mail\Backup\old\WindowsMail.MSMessageStore',
                'C:\Users\mp\AppData\Local\Microsoft\Windows Mail\Backup\old\WindowsMail.pat',
                'C:\Users\mp\AppData\Local\Microsoft\Windows Mail\Backup\old',
                'C:\Users\mp\AppData\Local\Microsoft\Windows Mail\edb00001.log',
                'C:\Users\mp\AppData\Local\Temp\CabF8E.tmp',
                'C:\Users\mp\AppData\Local\Temp\TarF8F.tmp',
                'C:\Users\mp\AppData\Local\Temp\ppcrlui_3164_2.ui',
                'C:\Users\mp\AppData\Local\Temp\ppcrlui_3164_2',
                'C:\Users\mp\AppData\Local\Microsoft\Windows Mail\edbtmp.log']
        self.score = 0
        self.accuracy = 0
        self.origorder = ['"C:\Program Files\Internet Explorer\iexplore.exe","SetValueKey","HKCU\Software\Microsoft\Internet Explorer\LowRegistry\ErrorReporting\LastShipAssertTime"',
                '"C:\Program Files\Internet Explorer\iexplore.exe","Write","C:\Users\mp\AppData\Local\Temp\\fqcuk.dll"',
                '"C:\Program Files\Internet Explorer\iexplore.exe","created","2924","C:\Users\mp\AppData\Local\Temp\\fqcuk.dll"',
                '"C:\Users\mp\AppData\Local\Temp\\fqcuk.dll","created","2936","C:\Users\mp\AppData\Local\Temp\\fqcuk.dll"',
                '"C:\Users\mp\AppData\Local\Temp\\fqcuk.dll","Write","C:\Users\mp\AppData\Roaming\Qohezy\zeve.exe"',
                '"C:\Program Files\Internet Explorer\iexplore.exe","terminated","2924","C:\Users\mp\AppData\Local\Temp\\fqcuk.dll"',
                '"UNKNOWN","created","2924","C:\Users\mp\AppData\Local\Temp\\fqcuk.dll"',
                '"C:\Users\mp\AppData\Local\Temp\\fqcuk.dll","SetValueKey","HKCU"',
                '"C:\Windows\System32\svchost.exe","SetValueKey","\REGISTRY\A\{511E200C-167F-11E4-9376-080027E9ED50}\DefaultObjectStore\IndexTable\FileIdIndex-{41003fa5-89a3-11e3-bfdc-806e6f6e6963}\_IndexName_"',
                '"C:\Windows\System32\svchost.exe","SetValueKey","\REGISTRY\A\{511E200C-167F-11E4-9376-080027E9ED50}\DefaultObjectStore\_CurrentObjectId_"',
                '"C:\Windows\System32\svchost.exe","SetValueKey","\REGISTRY\A\{511E200C-167F-11E4-9376-080027E9ED50}\DefaultObjectStore\ObjectTable\\13D\_ObjectId_"',
                '"C:\Windows\System32\svchost.exe","SetValueKey","\REGISTRY\A\{511E200C-167F-11E4-9376-080027E9ED50}\DefaultObjectStore\LruList\CurrentLru"',
                '"C:\Windows\System32\svchost.exe","SetValueKey","\REGISTRY\A\{511E200C-167F-11E4-9376-080027E9ED50}\DefaultObjectStore\LruList\\0000000000000B73\ObjectId"',
                '"C:\Windows\System32\svchost.exe","SetValueKey","\REGISTRY\A\{511E200C-167F-11E4-9376-080027E9ED50}\DefaultObjectStore\LruList\\0000000000000B73\ObjectLru"',
                '"C:\Windows\System32\svchost.exe","SetValueKey","\REGISTRY\A\{511E200C-167F-11E4-9376-080027E9ED50}\DefaultObjectStore\ObjectTable\\13D\_ObjectLru_"',
                '"C:\Windows\System32\svchost.exe","SetValueKey","\REGISTRY\A\{511E200C-167F-11E4-9376-080027E9ED50}\DefaultObjectStore\ObjectTable\\13D\_FileId_"',
                '"C:\Windows\System32\svchost.exe","SetValueKey","\REGISTRY\A\{511E200C-167F-11E4-9376-080027E9ED50}\DefaultObjectStore\ObjectTable\\13D\_Usn_"',
                '"C:\Windows\System32\svchost.exe","SetValueKey","\REGISTRY\A\{511E200C-167F-11E4-9376-080027E9ED50}\DefaultObjectStore\ObjectTable\\13D\_UsnJournalId_"',
                '"C:\Windows\System32\svchost.exe","SetValueKey","\REGISTRY\A\{511E200C-167F-11E4-9376-080027E9ED50}\DefaultObjectStore\ObjectTable\\13D\Indexes\FileIdIndex-{41003fa5-89a3-11e3-bfdc-806e6f6e6963}\900000000A149"',
                '"C:\Windows\System32\svchost.exe","SetValueKey","\REGISTRY\A\{511E200C-167F-11E4-9376-080027E9ED50}\DefaultObjectStore\IndexTable\FileIdIndex-{41003fa5-89a3-11e3-bfdc-806e6f6e6963}\900000000A149\\13D"',
                '"C:\Windows\System32\svchost.exe","SetValueKey","\REGISTRY\A\{511E200C-167F-11E4-9376-080027E9ED50}\DefaultObjectStore\ObjectTable\\13D\AeFileID"',
                '"C:\Windows\System32\svchost.exe","SetValueKey","\REGISTRY\A\{511E200C-167F-11E4-9376-080027E9ED50}\DefaultObjectStore\ObjectTable\\13D\AeProgramID"',
                '"C:\Windows\System32\svchost.exe","Write","C:\Windows\AppCompat\Programs\RecentFileCache.bcf"',
                '"C:\Users\mp\AppData\Local\Temp\\fqcuk.dll","Write","C:\Users\mp\AppData\Local\Temp\\tmp4632b6f2.bat"',
                '"UNKNOWN","created","2992","C:\Users\mp\AppData\Roaming\Qohezy\zeve.exe"',
                '"C:\Users\mp\AppData\Roaming\Qohezy\zeve.exe","SetValueKey","HKCU"',
                '"UNKNOWN","Write","C:\Program Files\Capture\logs\deleted_files\C\Users\mp\AppData\Local\Temp\\tmp4632b6f2.bat"',
                '"System","Write","C:\Program Files\Capture\logs\deleted_files\C\Users\mp\AppData\Local\Temp\\tmp4632b6f2.bat"',
                '"C:\Windows\System32\svchost.exe","created","3164","C:\Program Files\Windows Mail\WinMail.exe"',
                '"C:\Program Files\Internet Explorer\iexplore.exe","Write","C:\Users\mp\AppData\Local\Temp\BHDG.dll"',
                '"C:\Windows\explorer.exe","SetValueKey","HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\\3\\1406"',
                '"C:\Windows\explorer.exe","SetValueKey","HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings\Lockdown_Zones\\0\\1609"',
                '"C:\Windows\explorer.exe","SetValueKey","HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\\1\\1609"',
                '"C:\Windows\explorer.exe","SetValueKey","HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\\4\\1A02"',
                '"C:\Windows\explorer.exe","SetValueKey","HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\\2\\1A10"',
                '"C:\Windows\explorer.exe","SetValueKey","HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\\4\\1A10"',
                '"C:\Windows\explorer.exe","SetValueKey","HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\\4\\1A03"',
                '"C:\Windows\explorer.exe","SetValueKey","HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\\3\\1A05"',
                '"C:\Windows\explorer.exe","SetValueKey","HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\\4\\1A05"',
                '"C:\Windows\explorer.exe","SetValueKey","HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\\4\\1A06"',
                '"C:\Windows\explorer.exe","SetValueKey","HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings\WarnonBadCertRecving"',
                '"C:\Windows\explorer.exe","SetValueKey","HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings\EnableSPDY3_0"',
                '"C:\Windows\System32\\taskhost.exe","DeleteValueKey","HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings\ZoneMap\ProxyBypass"',
                '"C:\Windows\System32\\taskhost.exe","DeleteValueKey","HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Internet Settings\ZoneMap\ProxyBypass"',
                '"C:\Windows\System32\\taskhost.exe","DeleteValueKey","HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings\ZoneMap\IntranetName"',
                '"C:\Windows\System32\\taskhost.exe","DeleteValueKey","HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Internet Settings\ZoneMap\IntranetName"',
                '"C:\Windows\System32\\taskhost.exe","SetValueKey","HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings\ZoneMap\UNCAsIntranet"',
                '"C:\Windows\System32\\taskhost.exe","SetValueKey","HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings\ZoneMap\AutoDetect"',
                '"C:\Windows\System32\\taskhost.exe","DeleteValueKey","HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings\ZoneMap\ProxyBypass"',
                '"C:\Windows\System32\\taskhost.exe","DeleteValueKey","HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Internet Settings\ZoneMap\ProxyBypass"',
                '"C:\Windows\System32\\taskhost.exe","DeleteValueKey","HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings\ZoneMap\IntranetName"',
                '"C:\Windows\System32\\taskhost.exe","DeleteValueKey","HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Internet Settings\ZoneMap\IntranetName"',
                '"C:\Windows\System32\\taskhost.exe","SetValueKey","HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings\ZoneMap\UNCAsIntranet"',
                '"C:\Windows\System32\\taskhost.exe","SetValueKey","HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings\ZoneMap\AutoDetect"',
                '"C:\Windows\System32\\taskhost.exe","SetValueKey","HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\\0\\1609"',
                '"C:\Windows\System32\\taskhost.exe","SetValueKey","HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings\WarnonBadCertRecving"',
                '"C:\Windows\System32\\taskhost.exe","SetValueKey","HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings\EnableSPDY3_0"',
                '"C:\Windows\explorer.exe","SetValueKey","HKCU\Software\Microsoft\Nylaiw\Fauzwua"',
                '"C:\Windows\explorer.exe","SetValueKey","HKCU\Software\Microsoft\Nylaiw\Upcaolap"',
                '"C:\Windows\System32\\taskhost.exe","SetValueKey","HKCU\Software\Microsoft\Nylaiw\Fauzwua"',
                '"C:\Windows\System32\\taskhost.exe","SetValueKey","HKCU\Software\Microsoft\Nylaiw\Upcaolap"',
                '"C:\Windows\explorer.exe","SetValueKey","HKCU\Software\Microsoft\Nylaiw\Upcaolap"',
                '"C:\Windows\explorer.exe","DeleteValueKey","HKCU\Software\Microsoft\Windows\CurrentVersion\Run\zeve.exe"',
                '"C:\Windows\explorer.exe","SetValueKey","HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings\ProxyEnable"',
                '"C:\Windows\explorer.exe","DeleteValueKey","HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings\ProxyServer"',
                '"C:\Windows\explorer.exe","DeleteValueKey","HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings\ProxyOverride"',
                '"C:\Windows\explorer.exe","DeleteValueKey","HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings\AutoConfigURL"',
                '"C:\Windows\explorer.exe","SetValueKey","HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings\Connections\SavedLegacySettings"',
                '"C:\Program Files\Capture\CaptureClient.exe","DeleteValueKey","HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings\ZoneMap\ProxyBypass"',
                '"C:\Program Files\Capture\CaptureClient.exe","DeleteValueKey","HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Internet Settings\ZoneMap\ProxyBypass"',
                '"C:\Program Files\Capture\CaptureClient.exe","DeleteValueKey","HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings\ZoneMap\IntranetName"',
                '"C:\Program Files\Capture\CaptureClient.exe","DeleteValueKey","HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Internet Settings\ZoneMap\IntranetName"',
                '"C:\Program Files\Capture\CaptureClient.exe","SetValueKey","HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings\ZoneMap\UNCAsIntranet"',
                '"C:\Program Files\Capture\CaptureClient.exe","SetValueKey","HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings\ZoneMap\AutoDetect"',
                '"C:\Program Files\Capture\CaptureClient.exe","DeleteValueKey","HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings\ZoneMap\ProxyBypass"',
                '"C:\Program Files\Capture\CaptureClient.exe","DeleteValueKey","HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Internet Settings\ZoneMap\ProxyBypass"',
                '"C:\Program Files\Capture\CaptureClient.exe","DeleteValueKey","HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings\ZoneMap\IntranetName"',
                '"C:\Program Files\Capture\CaptureClient.exe","DeleteValueKey","HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Internet Settings\ZoneMap\IntranetName"',
                '"C:\Program Files\Capture\CaptureClient.exe","SetValueKey","HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings\ZoneMap\UNCAsIntranet"',
                '"C:\Program Files\Capture\CaptureClient.exe","SetValueKey","HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings\ZoneMap\AutoDetect"',
                '"C:\Program Files\Capture\CaptureClient.exe","SetValueKey","HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings\WarnonBadCertRecving"',
                '"C:\Program Files\Capture\CaptureClient.exe","SetValueKey","HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings\EnableSPDY3_0"',
                '"C:\Program Files\Capture\CaptureClient.exe","SetValueKey","HKCU\Software\Microsoft\Nylaiw\Fauzwua"',
                '"C:\Program Files\Internet Explorer\iexplore.exe","SetValueKey","HKCU\Software\Microsoft\Nylaiw\Fauzwua"',
                '"C:\Users\mp\AppData\Local\Temp\BHDG.dll","DeleteValueKey","HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings\ZoneMap\ProxyBypass"',
                '"C:\Users\mp\AppData\Local\Temp\BHDG.dll","DeleteValueKey","HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Internet Settings\ZoneMap\ProxyBypass"',
                '"C:\Users\mp\AppData\Local\Temp\BHDG.dll","DeleteValueKey","HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings\ZoneMap\IntranetName"',
                '"C:\Users\mp\AppData\Local\Temp\BHDG.dll","DeleteValueKey","HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Internet Settings\ZoneMap\IntranetName"',
                '"C:\Users\mp\AppData\Local\Temp\BHDG.dll","SetValueKey","HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings\ZoneMap\UNCAsIntranet"',
                '"C:\Users\mp\AppData\Local\Temp\BHDG.dll","SetValueKey","HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings\ZoneMap\AutoDetect"',
                '"C:\Users\mp\AppData\Local\Temp\BHDG.dll","DeleteValueKey","HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings\ZoneMap\ProxyBypass"',
                '"C:\Users\mp\AppData\Local\Temp\BHDG.dll","DeleteValueKey","HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Internet Settings\ZoneMap\ProxyBypass"',
                '"C:\Users\mp\AppData\Local\Temp\BHDG.dll","DeleteValueKey","HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings\ZoneMap\IntranetName"',
                '"C:\Users\mp\AppData\Local\Temp\BHDG.dll","DeleteValueKey","HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Internet Settings\ZoneMap\IntranetName"',
                '"C:\Users\mp\AppData\Local\Temp\BHDG.dll","SetValueKey","HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings\ZoneMap\UNCAsIntranet"',
                '"C:\Users\mp\AppData\Local\Temp\BHDG.dll","SetValueKey","HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings\ZoneMap\AutoDetect"',
                '"C:\Users\mp\AppData\Local\Temp\BHDG.dll","SetValueKey","HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings\WarnonBadCertRecving"',
                '"C:\Users\mp\AppData\Local\Temp\BHDG.dll","SetValueKey","HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings\EnableSPDY3_0"',
                '"C:\Users\mp\AppData\Local\Temp\BHDG.dll","SetValueKey","HKCU\Software\Microsoft\Nylaiw\Fauzwua"',
                '"C:\Program Files\Windows Mail\WinMail.exe","SetValueKey","HKCU\Software\Microsoft\IAM\Accounts\ConnectionSettingsMigrated"',
                '"C:\Program Files\Windows Mail\WinMail.exe","SetValueKey","HKCU\Software\Microsoft\Windows Mail\Trident\Main\Move System Caret"',
                '"C:\Program Files\Windows Mail\WinMail.exe","SetValueKey","HKCU\Software\Microsoft\Windows Mail\StoreMigratedV5"',
                '"C:\Program Files\Windows Mail\WinMail.exe","SetValueKey","HKCU\Software\Microsoft\Windows Mail\Settings Upgraded"',
                '"C:\Program Files\Windows Mail\WinMail.exe","SetValueKey","HKCU\Software\Microsoft\Windows Mail\Mail\Safe Attachments"',
                '"C:\Program Files\Windows Mail\WinMail.exe","SetValueKey","HKCU\Software\Microsoft\Windows Mail\Mail\Secure Safe Attachments"',
                '"C:\Program Files\Windows Mail\WinMail.exe","SetValueKey","HKCU\Software\Microsoft\Windows Mail\Running"',
                '"C:\Program Files\Internet Explorer\iexplore.exe","created","3176","C:\Users\mp\AppData\Local\Temp\BHDG.dll"',
                '"C:\Program Files\Windows Mail\WinMail.exe","Write","C:\Users\mp\AppData\Local\Microsoft\Windows Mail\edb.log"',
                '"C:\Program Files\Windows Mail\WinMail.exe","SetValueKey","HKCU\Software\Microsoft\IAM\Default LDAP Account"',
                '"C:\Program Files\Windows Mail\WinMail.exe","SetValueKey","HKCU\Software\Microsoft\IAM\Server ID"',
                '"C:\Program Files\Windows Mail\WinMail.exe","DeleteValueKey","HKCU\Identities\Changing"',
                '"C:\Program Files\Windows Mail\WinMail.exe","DeleteValueKey","HKCU\Identities\IncomingID"',
                '"C:\Program Files\Windows Mail\WinMail.exe","DeleteValueKey","HKCU\Identities\OutgoingID"',
                '"C:\Program Files\Windows Mail\WinMail.exe","SetValueKey","HKCU\Identities\{ACC29697-975F-4790-9CF9-A615892A2859}\Identity Ordinal"',
                '"C:\Program Files\Windows Mail\WinMail.exe","SetValueKey","HKCU\Identities\Identity Ordinal"',
                '"C:\Program Files\Windows Mail\WinMail.exe","SetValueKey","HKCU\Software\Microsoft\Windows Mail\LastBackup"',
                '"C:\Program Files\Windows Mail\WinMail.exe","Write","C:\Users\mp\AppData\Local\Microsoft\Windows Mail\edb.log"',
                '"C:\Program Files\Windows Mail\WinMail.exe","Write","C:\Users\mp\AppData\Local\Microsoft\Windows Mail\WindowsMail.MSMessageStore"',
                '"C:\Program Files\Windows Mail\WinMail.exe","Write","C:\Users\mp\AppData\Local\Microsoft\Windows Mail\Backup\\temp\WindowsMail.MSMessageStore"',
                '"C:\Program Files\Windows Mail\WinMail.exe","Write","C:\Users\mp\AppData\Local\Microsoft\Windows Mail\\tmp.edb"',
                '"C:\Program Files\Windows Mail\WinMail.exe","Write","C:\Users\mp\AppData\Local\Microsoft\Windows Mail\edb.log"',
                '"C:\Program Files\Windows Mail\WinMail.exe","Write","C:\Users\mp\AppData\Local\Microsoft\Windows Mail\WindowsMail.MSMessageStore"',
                '"C:\Program Files\Windows Mail\WinMail.exe","Write","C:\Users\mp\AppData\Local\Microsoft\Windows Mail\WindowsMail.pat"',
                '"C:\Program Files\Windows Mail\WinMail.exe","Write","C:\Users\mp\AppData\Local\Microsoft\Windows Mail\Backup\\temp\WindowsMail.MSMessageStore"',
                '"C:\Program Files\Windows Mail\WinMail.exe","Write","C:\Users\mp\AppData\Local\Microsoft\Windows Mail\edb.log"',
                '"C:\Program Files\Windows Mail\WinMail.exe","Write","C:\Users\mp\AppData\Local\Microsoft\Windows Mail\edbtmp.log"',
                '"C:\Program Files\Windows Mail\WinMail.exe","Write","C:\Users\mp\AppData\Local\Microsoft\Windows Mail\WindowsMail.MSMessageStore"',
                '"C:\Program Files\Windows Mail\WinMail.exe","Write","C:\Users\mp\AppData\Local\Microsoft\Windows Mail\WindowsMail.pat"',
                '"C:\Windows\System32\dwm.exe","DeleteValueKey","HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings\ZoneMap\ProxyBypass"',
                '"C:\Windows\System32\dwm.exe","DeleteValueKey","HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Internet Settings\ZoneMap\ProxyBypass"',
                '"C:\Windows\System32\dwm.exe","DeleteValueKey","HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings\ZoneMap\IntranetName"',
                '"C:\Windows\System32\dwm.exe","DeleteValueKey","HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Internet Settings\ZoneMap\IntranetName"',
                '"C:\Windows\System32\dwm.exe","SetValueKey","HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings\ZoneMap\UNCAsIntranet"',
                '"C:\Windows\System32\dwm.exe","SetValueKey","HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings\ZoneMap\AutoDetect"',
                '"C:\Windows\System32\dwm.exe","DeleteValueKey","HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings\ZoneMap\ProxyBypass"',
                '"C:\Windows\System32\dwm.exe","DeleteValueKey","HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Internet Settings\ZoneMap\ProxyBypass"',
                '"C:\Windows\System32\dwm.exe","DeleteValueKey","HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings\ZoneMap\IntranetName"',
                '"C:\Windows\System32\dwm.exe","DeleteValueKey","HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Internet Settings\ZoneMap\IntranetName"',
                '"C:\Windows\System32\dwm.exe","SetValueKey","HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings\ZoneMap\UNCAsIntranet"',
                '"C:\Windows\System32\dwm.exe","SetValueKey","HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings\ZoneMap\AutoDetect"',
                '"C:\Windows\System32\dwm.exe","SetValueKey","HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings\WarnonBadCertRecving"',
                '"C:\Windows\System32\dwm.exe","SetValueKey","HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings\EnableSPDY3_0"',
                '"C:\Windows\System32\dwm.exe","SetValueKey","HKCU\Software\Microsoft\Nylaiw\Fauzwua"',
                '"C:\Program Files\Windows Mail\WinMail.exe","Write","C:\Users\mp\AppData\Local\Microsoft\Windows Mail\WindowsMail.pat"',
                '"C:\Program Files\Windows Mail\WinMail.exe","Write","C:\Users\mp\AppData\Local\Microsoft\Windows Mail\Backup\\temp\edb00002.log"',
                '"C:\Program Files\Windows Mail\WinMail.exe","Write","C:\Users\mp\AppData\Local\Microsoft\Windows Mail\Backup\\temp\WindowsMail.pat"',
                '"C:\Program Files\Windows Mail\WinMail.exe","Delete","C:\Users\mp\AppData\Local\Microsoft\Windows Mail\Backup\old\edb00001.log"',
                '"C:\Program Files\Windows Mail\WinMail.exe","Delete","C:\Users\mp\AppData\Local\Microsoft\Windows Mail\Backup\old\WindowsMail.MSMessageStore"',
                '"C:\Program Files\Windows Mail\WinMail.exe","Delete","C:\Users\mp\AppData\Local\Microsoft\Windows Mail\Backup\old\WindowsMail.pat"',
                '"C:\Program Files\Windows Mail\WinMail.exe","Delete","C:\Users\mp\AppData\Local\Microsoft\Windows Mail\Backup\old"',
                '"C:\Program Files\Windows Mail\WinMail.exe","Delete","C:\Users\mp\AppData\Local\Microsoft\Windows Mail\edb00001.log"',
                '"C:\Program Files\Windows Mail\WinMail.exe","Write","C:\Users\mp\AppData\Local\Microsoft\Windows Mail\WindowsMail.MSMessageStore"',
                '"C:\Program Files\Internet Explorer\iexplore.exe","SetValueKey","HKCU\Software\Microsoft\Nylaiw\Fauzwua"',
                '"C:\CaptureLoader\CaptureClientLoader.exe","DeleteValueKey","HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings\ZoneMap\ProxyBypass"',
                '"C:\CaptureLoader\CaptureClientLoader.exe","DeleteValueKey","HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Internet Settings\ZoneMap\ProxyBypass"',
                '"C:\CaptureLoader\CaptureClientLoader.exe","DeleteValueKey","HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings\ZoneMap\IntranetName"',
                '"C:\CaptureLoader\CaptureClientLoader.exe","DeleteValueKey","HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Internet Settings\ZoneMap\IntranetName"',
                '"C:\CaptureLoader\CaptureClientLoader.exe","SetValueKey","HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings\ZoneMap\UNCAsIntranet"',
                '"C:\CaptureLoader\CaptureClientLoader.exe","SetValueKey","HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings\ZoneMap\AutoDetect"',
                '"C:\CaptureLoader\CaptureClientLoader.exe","DeleteValueKey","HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings\ZoneMap\ProxyBypass"',
                '"C:\CaptureLoader\CaptureClientLoader.exe","DeleteValueKey","HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Internet Settings\ZoneMap\ProxyBypass"',
                '"C:\CaptureLoader\CaptureClientLoader.exe","DeleteValueKey","HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings\ZoneMap\IntranetName"',
                '"C:\CaptureLoader\CaptureClientLoader.exe","DeleteValueKey","HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Internet Settings\ZoneMap\IntranetName"',
                '"C:\CaptureLoader\CaptureClientLoader.exe","SetValueKey","HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings\ZoneMap\UNCAsIntranet"',
                '"C:\CaptureLoader\CaptureClientLoader.exe","SetValueKey","HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings\ZoneMap\AutoDetect"',
                '"C:\CaptureLoader\CaptureClientLoader.exe","SetValueKey","HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings\WarnonBadCertRecving"',
                '"C:\CaptureLoader\CaptureClientLoader.exe","SetValueKey","HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings\EnableSPDY3_0"',
                '"C:\CaptureLoader\CaptureClientLoader.exe","SetValueKey","HKCU\Software\Microsoft\Nylaiw\Fauzwua"',
                '"C:\Program Files\Windows Mail\WinMail.exe","SetValueKey","HKCU\Software\Microsoft\Windows Mail\V7StoreMigDone"',
                '"C:\Program Files\Windows Mail\WinMail.exe","DeleteValueKey","HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings\ZoneMap\ProxyBypass"',
                '"C:\Program Files\Windows Mail\WinMail.exe","DeleteValueKey","HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Internet Settings\ZoneMap\ProxyBypass"',
                '"C:\Program Files\Windows Mail\WinMail.exe","DeleteValueKey","HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings\ZoneMap\IntranetName"',
                '"C:\Program Files\Windows Mail\WinMail.exe","DeleteValueKey","HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Internet Settings\ZoneMap\IntranetName"',
                '"C:\Program Files\Windows Mail\WinMail.exe","SetValueKey","HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings\ZoneMap\UNCAsIntranet"',
                '"C:\Program Files\Windows Mail\WinMail.exe","SetValueKey","HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings\ZoneMap\AutoDetect"',
                '"C:\Program Files\Windows Mail\WinMail.exe","DeleteValueKey","HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings\ZoneMap\ProxyBypass"',
                '"C:\Program Files\Windows Mail\WinMail.exe","DeleteValueKey","HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Internet Settings\ZoneMap\ProxyBypass"',
                '"C:\Program Files\Windows Mail\WinMail.exe","DeleteValueKey","HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings\ZoneMap\IntranetName"',
                '"C:\Program Files\Windows Mail\WinMail.exe","DeleteValueKey","HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Internet Settings\ZoneMap\IntranetName"',
                '"C:\Program Files\Windows Mail\WinMail.exe","SetValueKey","HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings\ZoneMap\UNCAsIntranet"',
                '"C:\Program Files\Windows Mail\WinMail.exe","SetValueKey","HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings\ZoneMap\AutoDetect"',
                '"C:\Program Files\Windows Mail\WinMail.exe","SetValueKey","HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings\WarnonBadCertRecving"',
                '"C:\Program Files\Windows Mail\WinMail.exe","SetValueKey","HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings\EnableSPDY3_0"',
                '"C:\Program Files\Windows Mail\WinMail.exe","SetValueKey","HKCU\Software\Microsoft\Nylaiw\Fauzwua"',
                '"C:\Program Files\Windows Mail\WinMail.exe","Write","C:\Users\mp\AppData\Local\Microsoft\Windows Mail\edb.log"',
                '"C:\Program Files\Windows Mail\WinMail.exe","Write","C:\Users\mp\AppData\Local\Microsoft\Windows Mail\WindowsMail.MSMessageStore"',
                '"C:\Program Files\Windows Mail\WinMail.exe","Write","C:\Users\mp\AppData\Local\Microsoft\Windows Mail\Local Folders\Inbox\winmail.fol"',
                '"C:\Program Files\Windows Mail\WinMail.exe","Write","C:\Users\mp\AppData\Local\Microsoft\Windows Mail\edb.log"',
                '"C:\Program Files\Windows Mail\WinMail.exe","Write","C:\Users\mp\AppData\Local\Microsoft\Windows Mail\Local Folders\Outbox\winmail.fol"',
                '"C:\Program Files\Windows Mail\WinMail.exe","Write","C:\Users\mp\AppData\Local\Microsoft\Windows Mail\Local Folders\Sent Items\winmail.fol"',
                '"C:\Program Files\Windows Mail\WinMail.exe","Write","C:\Users\mp\AppData\Local\Microsoft\Windows Mail\Local Folders\Deleted Items\winmail.fol"',
                '"C:\Program Files\Windows Mail\WinMail.exe","Write","C:\Users\mp\AppData\Local\Microsoft\Windows Mail\Local Folders\Drafts\winmail.fol"',
                '"C:\Program Files\Windows Mail\WinMail.exe","Write","C:\Users\mp\AppData\Local\Microsoft\Windows Mail\Local Folders\Junk E-mail\winmail.fol"',
                '"C:\Program Files\Windows Mail\WinMail.exe","SetValueKey","HKCU\Software\Microsoft\IAM\Default News Account"',
                '"C:\Program Files\Windows Mail\WinMail.exe","Write","C:\Users\mp\AppData\Local\Microsoft\Windows Mail\WindowsMail.MSMessageStore"',
                '"C:\Program Files\Windows Mail\WinMail.exe","Write","C:\Users\mp\AppData\Local\Microsoft\Windows Mail\edb.log"',
                '"C:\Program Files\Windows Mail\WinMail.exe","Write","C:\Users\mp\AppData\Local\Microsoft\Windows Mail\WindowsMail.MSMessageStore"',
                '"C:\Program Files\Windows Mail\WinMail.exe","Write","C:\Users\mp\AppData\Local\Microsoft\Windows Mail\edb.log"',
                '"C:\Program Files\Windows Mail\WinMail.exe","Write","C:\Users\mp\AppData\Local\Microsoft\Windows Mail\WindowsMail.MSMessageStore"',
                '"C:\Program Files\Windows Mail\WinMail.exe","Write","C:\Users\mp\AppData\Local\Microsoft\Windows Mail\edb.log"',
                '"C:\Program Files\Windows Mail\WinMail.exe","Write","C:\Users\mp\AppData\Local\Microsoft\Windows Mail\WindowsMail.MSMessageStore"',
                '"C:\Program Files\Windows Mail\WinMail.exe","Write","C:\Users\mp\AppData\Local\Microsoft\Windows Mail\edb.log"',
                '"C:\Program Files\Windows Mail\WinMail.exe","Write","C:\Users\mp\AppData\Local\Microsoft\Windows Mail\WindowsMail.MSMessageStore"',
                '"C:\Program Files\Windows Mail\WinMail.exe","Write","C:\Users\mp\AppData\Local\Microsoft\Windows Mail\edb.log"',
                '"C:\Program Files\Windows Mail\WinMail.exe","Write","C:\Users\mp\AppData\Local\Microsoft\Windows Mail\WindowsMail.MSMessageStore"',
                '"C:\Program Files\Windows Mail\WinMail.exe","Write","C:\Users\mp\AppData\Local\Microsoft\Windows Mail\edb.log"',
                '"C:\Program Files\Windows Mail\WinMail.exe","Write","C:\Users\mp\AppData\Local\Microsoft\Windows Mail\WindowsMail.MSMessageStore"',
                '"C:\Program Files\Windows Mail\WinMail.exe","Write","C:\Users\mp\AppData\Local\Microsoft\Windows Mail\edb.log"',
                '"C:\Program Files\Windows Mail\WinMail.exe","Write","C:\Users\mp\AppData\Local\Microsoft\Windows Mail\WindowsMail.MSMessageStore"',
                '"C:\Program Files\Windows Mail\WinMail.exe","Write","C:\Users\mp\AppData\Local\Microsoft\Windows Mail\edb.log"',
                '"C:\Program Files\Windows Mail\WinMail.exe","Write","C:\Users\mp\AppData\Local\Microsoft\Windows Mail\WindowsMail.MSMessageStore"',
                '"C:\Program Files\Windows Mail\WinMail.exe","Write","C:\Users\mp\AppData\Local\Microsoft\Windows Mail\edb.log"',
                '"C:\Program Files\Windows Mail\WinMail.exe","DeleteValueKey","HKCU\Software\Microsoft\WAB\NamedProps"',
                '"C:\Program Files\Windows Mail\WinMail.exe","DeleteValueKey","HKCU\Software\Microsoft\WAB\NamedPropCount"',
                '"C:\Program Files\Windows Mail\WinMail.exe","SetValueKey","HKCU\Software\Microsoft\WAB\NamedProps"',
                '"C:\Program Files\Windows Mail\WinMail.exe","SetValueKey","HKCU\Software\Microsoft\WAB\NamedPropCount"',
                '"C:\Program Files\Windows Mail\WinMail.exe","DeleteValueKey","HKCU\Software\Microsoft\WAB\NamedProps"',
                '"C:\Program Files\Windows Mail\WinMail.exe","DeleteValueKey","HKCU\Software\Microsoft\WAB\NamedPropCount"',
                '"C:\Program Files\Windows Mail\WinMail.exe","SetValueKey","HKCU\Software\Microsoft\WAB\NamedProps"',
                '"C:\Program Files\Windows Mail\WinMail.exe","SetValueKey","HKCU\Software\Microsoft\WAB\NamedPropCount"',
                '"C:\Program Files\Windows Mail\WinMail.exe","DeleteValueKey","HKCU\Software\Microsoft\WAB\NamedProps"',
                '"C:\Program Files\Windows Mail\WinMail.exe","DeleteValueKey","HKCU\Software\Microsoft\WAB\NamedPropCount"',
                '"C:\Program Files\Windows Mail\WinMail.exe","SetValueKey","HKCU\Software\Microsoft\WAB\NamedProps"',
                '"C:\Program Files\Windows Mail\WinMail.exe","SetValueKey","HKCU\Software\Microsoft\WAB\NamedPropCount"',
                '"C:\Program Files\Windows Mail\WinMail.exe","DeleteValueKey","HKCU\Software\Microsoft\WAB\NamedProps"',
                '"C:\Program Files\Windows Mail\WinMail.exe","DeleteValueKey","HKCU\Software\Microsoft\WAB\NamedPropCount"',
                '"C:\Program Files\Windows Mail\WinMail.exe","SetValueKey","HKCU\Software\Microsoft\WAB\NamedProps"',
                '"C:\Program Files\Windows Mail\WinMail.exe","SetValueKey","HKCU\Software\Microsoft\WAB\NamedPropCount"',
                '"C:\Program Files\Windows Mail\WinMail.exe","Write","C:\Users\mp\AppData\Local\Microsoft\Windows Mail\WindowsMail.MSMessageStore"',
                '"C:\Program Files\Windows Mail\WinMail.exe","Write","C:\Users\mp\AppData\Local\Microsoft\Windows Mail\Local Folders\Inbox\\4F8B02F0-00000001.eml"',
                '"C:\Program Files\Windows Mail\WinMail.exe","SetValueKey","HKCU\Software\Microsoft\Windows Mail\Mail\Welcome Message"',
                '"C:\Program Files\Windows Mail\WinMail.exe","SetValueKey","HKCU\Software\Microsoft\Windows Mail\Junk Mail\Safe Senders List\Version"',
                '"C:\Program Files\Windows Mail\WinMail.exe","SetValueKey","HKCU\Software\Microsoft\Windows Mail\Junk Mail\Block Senders List\Version"',
                '"C:\Program Files\Windows Mail\WinMail.exe","Write","C:\Users\mp\AppData\Local\Microsoft\Windows Mail\edb.log"',
                '"C:\Program Files\Windows Mail\WinMail.exe","Write","C:\Users\mp\AppData\Local\Microsoft\Windows Mail\WindowsMail.MSMessageStore"',
                '"C:\Program Files\Windows Mail\WinMail.exe","SetValueKey","HKCU\Software\Microsoft\IdentityCRL\Dynamic Salt\Value"',
                '"C:\Program Files\Windows Mail\WinMail.exe","SetValueKey","HKCU\Software\Microsoft\IdentityCRL\Dynamic Salt\Size"',
                '"C:\Windows\System32\lsass.exe","Write","C:\Users\mp\AppData\Roaming\Microsoft\Protect\S-1-5-21-78034117-1329648361-637219273-1001\\3aed1323-c5d3-4c4a-979c-78f92d2e3e2b"',
                '"C:\Windows\System32\lsass.exe","Write","C:\Users\mp\AppData\Roaming\Microsoft\Protect\S-1-5-21-78034117-1329648361-637219273-1001\Preferred"',
                '"C:\Program Files\Windows Mail\WinMail.exe","Write","C:\Users\mp\AppData\Local\Microsoft\Windows Mail\WindowsMail.MSMessageStore"',
                '"C:\Program Files\Windows Mail\WinMail.exe","SetValueKey","HKCR\Local Settings\MuiCache\B\\52C64B7E\LanguageList"',
                '"C:\Program Files\Windows Mail\WinMail.exe","Write","C:\Users\mp\AppData\Local\Microsoft\Windows Mail\edb.log"',
                '"C:\Program Files\Windows Mail\WinMail.exe","Write","C:\Users\mp\AppData\Local\Microsoft\Windows Mail\WindowsMail.MSMessageStore"',
                '"C:\Program Files\Windows Mail\WinMail.exe","Write","C:\Users\mp\AppData\LocalLow\Microsoft\CryptnetUrlCache\MetaData\E6024EAC88E6B6165D49FE3C95ADD735"',
                '"C:\Program Files\Windows Mail\WinMail.exe","Write","C:\Users\mp\AppData\LocalLow\Microsoft\CryptnetUrlCache\Content\E6024EAC88E6B6165D49FE3C95ADD735"',
                '"C:\Program Files\Windows Mail\WinMail.exe","Write","C:\Users\mp\AppData\LocalLow\Microsoft\CryptnetUrlCache\MetaData\E6024EAC88E6B6165D49FE3C95ADD735"',
                '"C:\Program Files\Windows Mail\WinMail.exe","Write","C:\Users\mp\AppData\Local\Temp\CabF8E.tmp"',
                '"C:\Program Files\Windows Mail\WinMail.exe","Write","C:\Users\mp\AppData\Local\Temp\TarF8F.tmp"',
                '"C:\Program Files\Windows Mail\WinMail.exe","Delete","C:\Users\mp\AppData\Local\Temp\CabF8E.tmp"',
                '"C:\Program Files\Windows Mail\WinMail.exe","Delete","C:\Users\mp\AppData\Local\Temp\TarF8F.tmp"',
                '"C:\Program Files\Windows Mail\WinMail.exe","Write","C:\Users\mp\AppData\Local\Microsoft\Windows Mail\Local Folders\Inbox\\4F8B02F0-00000001.eml:OECustomProperty"',
                '"C:\Program Files\Windows Mail\WinMail.exe","Write","C:\Users\mp\AppData\Local\Temp\ppcrlui_3164_2"',
                '"C:\Program Files\Windows Mail\WinMail.exe","Delete","C:\Users\mp\AppData\Local\Temp\ppcrlui_3164_2.ui"',
                '"C:\Program Files\Windows Mail\WinMail.exe","Delete","C:\Users\mp\AppData\Local\Temp\ppcrlui_3164_2"',
                '"C:\Program Files\Windows Mail\WinMail.exe","SetValueKey","HKCU\Software\Microsoft\Windows Mail\SpoolerDlgPos"',
                '"C:\Program Files\Windows Mail\WinMail.exe","SetValueKey","HKCU\Software\Microsoft\Windows Mail\SpoolerTack"',
                '"C:\Program Files\Windows Mail\WinMail.exe","SetValueKey","HKCU\Software\Microsoft\Windows Mail\Mail\Default_CodePage"',
                '"C:\Program Files\Windows Mail\WinMail.exe","Write","C:\Users\mp\AppData\Local\Microsoft\Windows Mail\WindowsMail.MSMessageStore"',
                '"C:\Program Files\Windows Mail\WinMail.exe","Write","C:\Users\mp\AppData\Local\Microsoft\Windows Mail\edb.chk"',
                '"C:\Program Files\Windows Mail\WinMail.exe","Write","C:\Users\mp\AppData\Local\Microsoft\Windows Mail\edb.log"',
                '"C:\Program Files\Windows Mail\WinMail.exe","Write","C:\Users\mp\AppData\Local\Microsoft\Windows Mail\WindowsMail.MSMessageStore"',
                '"C:\Program Files\Windows Mail\WinMail.exe","Write","C:\Users\mp\AppData\Local\Microsoft\Windows Mail\edb.chk"',
                '"C:\Program Files\Windows Mail\WinMail.exe","Write","C:\Users\mp\AppData\Local\Microsoft\Windows Mail\edb.log"',
                '"C:\Program Files\Windows Mail\WinMail.exe","SetValueKey","HKCU\Software\Microsoft\Windows Mail\Compact Check Count"',
                '"C:\Program Files\Windows Mail\WinMail.exe","SetValueKey","HKCU\Software\Microsoft\Windows Mail\LastRun"',
                '"C:\Program Files\Windows Mail\WinMail.exe","SetValueKey","HKCU\Software\Microsoft\Windows Mail\Running"',
                '"C:\Program Files\Windows Mail\WinMail.exe","Write","C:\Users\mp\AppData\Local\Microsoft\Windows Mail\WindowsMail.MSMessageStore"',
                '"C:\Program Files\Windows Mail\WinMail.exe","Write","C:\Users\mp\AppData\Local\Microsoft\Windows Mail\edb.log"',
                '"C:\Program Files\Windows Mail\WinMail.exe","Write","C:\Users\mp\AppData\Local\Microsoft\Windows Mail\edb.chk"',
                '"C:\Program Files\Windows Mail\WinMail.exe","Delete","C:\Users\mp\AppData\Local\Microsoft\Windows Mail\edbtmp.log"',
                '"C:\Windows\explorer.exe","SetValueKey","HKCU\Software\Microsoft\Nylaiw\Upcaolap"',
                '"C:\Windows\System32\\taskhost.exe","SetValueKey","HKCU\Software\Microsoft\Nylaiw\Upcaolap"',
                '"C:\Program Files\Capture\CaptureClient.exe","SetValueKey","HKCU\Software\Microsoft\Nylaiw\Upcaolap"',
                '"C:\Program Files\Internet Explorer\iexplore.exe","SetValueKey","HKCU\Software\Microsoft\Nylaiw\Upcaolap"',
                '"C:\Users\mp\AppData\Local\Temp\BHDG.dll","SetValueKey","HKCU\Software\Microsoft\Nylaiw\Upcaolap"',
                '"C:\Windows\System32\dwm.exe","SetValueKey","HKCU\Software\Microsoft\Nylaiw\Upcaolap"',
                '"C:\Program Files\Internet Explorer\iexplore.exe","SetValueKey","HKCU\Software\Microsoft\Nylaiw\Upcaolap"',
                '"C:\CaptureLoader\CaptureClientLoader.exe","SetValueKey","HKCU\Software\Microsoft\Nylaiw\Upcaolap"',
                '"C:\Program Files\Windows Mail\WinMail.exe","SetValueKey","HKCU\Software\Microsoft\Nylaiw\Upcaolap"',
                '"C:\Windows\System32\\taskhost.exe","SetValueKey","HKCU\Software\Microsoft\Nylaiw\Upcaolap"',
                '"C:\Users\mp\AppData\Local\Temp\\fqcuk.dll","terminated","2936","C:\Users\mp\AppData\Local\Temp\\fqcuk.dll"',
                '"C:\Users\mp\AppData\Local\Temp\BHDG.dll","created","3396","C:\Users\mp\AppData\Local\Temp\BHDG.dll"',
                '"C:\Users\mp\AppData\Local\Temp\BHDG.dll","SetValueKey","HKCU"',
                '"C:\Program Files\Internet Explorer\iexplore.exe","SetValueKey","HKCU\Software\Microsoft\Nylaiw\Fauzwua"',
                '"C:\Program Files\Internet Explorer\iexplore.exe","SetValueKey","HKCU\Software\Microsoft\Nylaiw\Upcaolap"',
                '"UNKNOWN","terminated","2992","C:\Users\mp\AppData\Roaming\Qohezy\zeve.exe"']
        self.outbuff = []

    def getacc(self):
        accscore = 0.0
        if not self.outbuff or not self.origorder:
            return 0 
        else:
           # print self.outbuff[0]
            for i in range(0, len(self.outbuff)):
                if i < len(self.origorder):
                    if self.origorder[i] != self.outbuff[i]:
                        self.outbuff.insert(i, "0")
            for i in range(0, len(self.outbuff)):
                if i < len(self.origorder):
                    #print "comparing " + self.outbuff[i] + " and " + self.origorder[i]
                    if self.outbuff[i] == self.origorder[i]:
                    #    print "match"
                        accscore += 1
                    else:
                        pass
                else:
                    break
        if accscore == 0:
            return 0
        else:
            self.accuracy = accscore / len(self.origorder) * 100
            #print self.accuracy
        return self.accuracy
